// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dct,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-1-e,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.143000,HLS_SYN_LAT=1723,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=1,HLS_SYN_FF=223,HLS_SYN_LUT=1281}" *)

module dct (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_pp0_stage0 = 6'd2;
parameter    ap_ST_fsm_state4 = 6'd4;
parameter    ap_ST_fsm_state5 = 6'd8;
parameter    ap_ST_fsm_pp1_stage0 = 6'd16;
parameter    ap_ST_fsm_state8 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] input_r_address0;
output   input_r_ce0;
input  [15:0] input_r_q0;
output  [5:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [15:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [6:0] indvar_flatten_reg_120;
reg   [3:0] r_i_reg_131;
reg   [3:0] c_i_reg_142;
reg   [6:0] indvar_flatten2_reg_153;
reg   [3:0] r_i2_reg_164;
reg   [3:0] c_i6_reg_175;
wire   [0:0] exitcond_flatten_fu_194_p2;
reg   [0:0] exitcond_flatten_reg_391;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [6:0] indvar_flatten_next_fu_200_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [3:0] c_i_mid2_fu_218_p3;
reg   [3:0] c_i_mid2_reg_400;
wire   [3:0] tmp_i_mid2_v_v_fu_226_p3;
reg   [3:0] tmp_i_mid2_v_v_reg_405;
wire   [3:0] c_fu_261_p2;
wire   [0:0] exitcond_flatten2_fu_292_p2;
reg   [0:0] exitcond_flatten2_reg_421;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state6_pp1_stage0_iter0;
wire    ap_block_state7_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [6:0] indvar_flatten_next2_fu_298_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [3:0] tmp_i4_mid2_v_fu_324_p3;
reg   [3:0] tmp_i4_mid2_v_reg_430;
wire   [5:0] tmp_4_i_fu_375_p2;
reg   [5:0] tmp_4_i_reg_440;
wire   [3:0] c_1_fu_381_p2;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire    ap_CS_fsm_state5;
wire    grp_dct_2d_fu_186_ap_done;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state6;
reg    ap_enable_reg_pp1_iter1;
reg   [5:0] buf_2d_in_address0;
reg    buf_2d_in_ce0;
reg    buf_2d_in_we0;
wire   [15:0] buf_2d_in_q0;
reg   [5:0] buf_2d_out_address0;
reg    buf_2d_out_ce0;
reg    buf_2d_out_we0;
wire   [15:0] buf_2d_out_q0;
wire    grp_dct_2d_fu_186_ap_start;
wire    grp_dct_2d_fu_186_ap_idle;
wire    grp_dct_2d_fu_186_ap_ready;
wire   [5:0] grp_dct_2d_fu_186_in_block_address0;
wire    grp_dct_2d_fu_186_in_block_ce0;
wire   [5:0] grp_dct_2d_fu_186_out_block_address0;
wire    grp_dct_2d_fu_186_out_block_ce0;
wire    grp_dct_2d_fu_186_out_block_we0;
wire   [15:0] grp_dct_2d_fu_186_out_block_d0;
reg   [3:0] ap_phi_mux_r_i_phi_fu_135_p4;
wire    ap_block_pp0_stage0;
reg   [3:0] ap_phi_mux_r_i2_phi_fu_168_p4;
wire    ap_block_pp1_stage0;
reg    ap_reg_grp_dct_2d_fu_186_ap_start;
wire    ap_CS_fsm_state4;
wire   [63:0] tmp_i_fu_256_p1;
wire   [63:0] tmp_31_cast_fu_287_p1;
wire   [63:0] tmp_35_cast_fu_370_p1;
wire   [63:0] tmp_5_i_fu_387_p1;
wire   [0:0] exitcond_i_fu_212_p2;
wire   [3:0] r_fu_206_p2;
wire   [2:0] tmp_fu_234_p1;
wire   [5:0] c_i_cast6_fu_246_p1;
wire   [5:0] tmp_i_mid2_fu_238_p3;
wire   [5:0] tmp_9_i_fu_250_p2;
wire   [6:0] tmp_s_fu_267_p3;
wire   [7:0] tmp_30_cast_fu_274_p1;
wire   [7:0] tmp_1_i_cast_fu_278_p1;
wire   [7:0] tmp_22_fu_281_p2;
wire   [0:0] exitcond_i1_fu_310_p2;
wire   [3:0] r_1_fu_304_p2;
wire   [6:0] tmp_23_fu_332_p3;
wire   [2:0] tmp_3_fu_344_p1;
wire   [3:0] c_i6_mid2_fu_316_p3;
wire   [7:0] tmp_33_cast_fu_340_p1;
wire   [7:0] tmp_3_i_cast_fu_360_p1;
wire   [7:0] tmp_24_fu_364_p2;
wire   [5:0] c_i6_cast2_fu_356_p1;
wire   [5:0] tmp_1_i5_mid2_fu_348_p3;
wire    ap_CS_fsm_state8;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_reg_grp_dct_2d_fu_186_ap_start = 1'b0;
end

dct_2d_row_outbuf #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
buf_2d_in_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_2d_in_address0),
    .ce0(buf_2d_in_ce0),
    .we0(buf_2d_in_we0),
    .d0(input_r_q0),
    .q0(buf_2d_in_q0)
);

dct_2d_row_outbuf #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
buf_2d_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_2d_out_address0),
    .ce0(buf_2d_out_ce0),
    .we0(buf_2d_out_we0),
    .d0(grp_dct_2d_fu_186_out_block_d0),
    .q0(buf_2d_out_q0)
);

dct_2d grp_dct_2d_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_2d_fu_186_ap_start),
    .ap_done(grp_dct_2d_fu_186_ap_done),
    .ap_idle(grp_dct_2d_fu_186_ap_idle),
    .ap_ready(grp_dct_2d_fu_186_ap_ready),
    .in_block_address0(grp_dct_2d_fu_186_in_block_address0),
    .in_block_ce0(grp_dct_2d_fu_186_in_block_ce0),
    .in_block_q0(buf_2d_in_q0),
    .out_block_address0(grp_dct_2d_fu_186_out_block_address0),
    .out_block_ce0(grp_dct_2d_fu_186_out_block_ce0),
    .out_block_we0(grp_dct_2d_fu_186_out_block_we0),
    .out_block_d0(grp_dct_2d_fu_186_out_block_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_condition_pp1_exit_iter0_state6) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (grp_dct_2d_fu_186_ap_done == 1'b1))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp1_exit_iter0_state6) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state6);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (grp_dct_2d_fu_186_ap_done == 1'b1))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_dct_2d_fu_186_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_reg_grp_dct_2d_fu_186_ap_start <= 1'b1;
        end else if ((grp_dct_2d_fu_186_ap_ready == 1'b1)) begin
            ap_reg_grp_dct_2d_fu_186_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (exitcond_flatten2_fu_292_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        c_i6_reg_175 <= c_1_fu_381_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_dct_2d_fu_186_ap_done == 1'b1))) begin
        c_i6_reg_175 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_194_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_i_reg_142 <= c_fu_261_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        c_i_reg_142 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (exitcond_flatten2_fu_292_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        indvar_flatten2_reg_153 <= indvar_flatten_next2_fu_298_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_dct_2d_fu_186_ap_done == 1'b1))) begin
        indvar_flatten2_reg_153 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_194_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_120 <= indvar_flatten_next_fu_200_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_120 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (exitcond_flatten2_reg_421 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        r_i2_reg_164 <= tmp_i4_mid2_v_reg_430;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_dct_2d_fu_186_ap_done == 1'b1))) begin
        r_i2_reg_164 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_reg_391 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        r_i_reg_131 <= tmp_i_mid2_v_v_reg_405;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        r_i_reg_131 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_194_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_i_mid2_reg_400 <= c_i_mid2_fu_218_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        exitcond_flatten2_reg_421 <= exitcond_flatten2_fu_292_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_flatten_reg_391 <= exitcond_flatten_fu_194_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (exitcond_flatten2_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        tmp_4_i_reg_440 <= tmp_4_i_fu_375_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (exitcond_flatten2_fu_292_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        tmp_i4_mid2_v_reg_430 <= tmp_i4_mid2_v_fu_324_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_194_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_i_mid2_v_v_reg_405 <= tmp_i_mid2_v_v_fu_226_p3;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_194_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_flatten2_fu_292_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state6 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten2_reg_421 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        ap_phi_mux_r_i2_phi_fu_168_p4 = tmp_i4_mid2_v_reg_430;
    end else begin
        ap_phi_mux_r_i2_phi_fu_168_p4 = r_i2_reg_164;
    end
end

always @ (*) begin
    if (((exitcond_flatten_reg_391 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_r_i_phi_fu_135_p4 = tmp_i_mid2_v_v_reg_405;
    end else begin
        ap_phi_mux_r_i_phi_fu_135_p4 = r_i_reg_131;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        buf_2d_in_address0 = tmp_31_cast_fu_287_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_in_address0 = grp_dct_2d_fu_186_in_block_address0;
    end else begin
        buf_2d_in_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        buf_2d_in_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_in_ce0 = grp_dct_2d_fu_186_in_block_ce0;
    end else begin
        buf_2d_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_reg_391 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        buf_2d_in_we0 = 1'b1;
    end else begin
        buf_2d_in_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        buf_2d_out_address0 = tmp_35_cast_fu_370_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_out_address0 = grp_dct_2d_fu_186_out_block_address0;
    end else begin
        buf_2d_out_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        buf_2d_out_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_out_ce0 = grp_dct_2d_fu_186_out_block_ce0;
    end else begin
        buf_2d_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_out_we0 = grp_dct_2d_fu_186_out_block_we0;
    end else begin
        buf_2d_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (exitcond_flatten2_reg_421 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((exitcond_flatten_fu_194_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((exitcond_flatten_fu_194_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_dct_2d_fu_186_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((exitcond_flatten2_fu_292_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((exitcond_flatten2_fu_292_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign c_1_fu_381_p2 = (4'd1 + c_i6_mid2_fu_316_p3);

assign c_fu_261_p2 = (4'd1 + c_i_mid2_fu_218_p3);

assign c_i6_cast2_fu_356_p1 = c_i6_mid2_fu_316_p3;

assign c_i6_mid2_fu_316_p3 = ((exitcond_i1_fu_310_p2[0:0] === 1'b1) ? 4'd0 : c_i6_reg_175);

assign c_i_cast6_fu_246_p1 = c_i_mid2_fu_218_p3;

assign c_i_mid2_fu_218_p3 = ((exitcond_i_fu_212_p2[0:0] === 1'b1) ? 4'd0 : c_i_reg_142);

assign exitcond_flatten2_fu_292_p2 = ((indvar_flatten2_reg_153 == 7'd64) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_194_p2 = ((indvar_flatten_reg_120 == 7'd64) ? 1'b1 : 1'b0);

assign exitcond_i1_fu_310_p2 = ((c_i6_reg_175 == 4'd8) ? 1'b1 : 1'b0);

assign exitcond_i_fu_212_p2 = ((c_i_reg_142 == 4'd8) ? 1'b1 : 1'b0);

assign grp_dct_2d_fu_186_ap_start = ap_reg_grp_dct_2d_fu_186_ap_start;

assign indvar_flatten_next2_fu_298_p2 = (indvar_flatten2_reg_153 + 7'd1);

assign indvar_flatten_next_fu_200_p2 = (indvar_flatten_reg_120 + 7'd1);

assign input_r_address0 = tmp_i_fu_256_p1;

assign output_r_address0 = tmp_5_i_fu_387_p1;

assign output_r_d0 = buf_2d_out_q0;

assign r_1_fu_304_p2 = (4'd1 + ap_phi_mux_r_i2_phi_fu_168_p4);

assign r_fu_206_p2 = (4'd1 + ap_phi_mux_r_i_phi_fu_135_p4);

assign tmp_1_i5_mid2_fu_348_p3 = {{tmp_3_fu_344_p1}, {3'd0}};

assign tmp_1_i_cast_fu_278_p1 = c_i_mid2_reg_400;

assign tmp_22_fu_281_p2 = (tmp_30_cast_fu_274_p1 + tmp_1_i_cast_fu_278_p1);

assign tmp_23_fu_332_p3 = {{tmp_i4_mid2_v_fu_324_p3}, {3'd0}};

assign tmp_24_fu_364_p2 = (tmp_33_cast_fu_340_p1 + tmp_3_i_cast_fu_360_p1);

assign tmp_30_cast_fu_274_p1 = tmp_s_fu_267_p3;

assign tmp_31_cast_fu_287_p1 = tmp_22_fu_281_p2;

assign tmp_33_cast_fu_340_p1 = tmp_23_fu_332_p3;

assign tmp_35_cast_fu_370_p1 = tmp_24_fu_364_p2;

assign tmp_3_fu_344_p1 = tmp_i4_mid2_v_fu_324_p3[2:0];

assign tmp_3_i_cast_fu_360_p1 = c_i6_mid2_fu_316_p3;

assign tmp_4_i_fu_375_p2 = (c_i6_cast2_fu_356_p1 + tmp_1_i5_mid2_fu_348_p3);

assign tmp_5_i_fu_387_p1 = tmp_4_i_reg_440;

assign tmp_9_i_fu_250_p2 = (c_i_cast6_fu_246_p1 + tmp_i_mid2_fu_238_p3);

assign tmp_fu_234_p1 = tmp_i_mid2_v_v_fu_226_p3[2:0];

assign tmp_i4_mid2_v_fu_324_p3 = ((exitcond_i1_fu_310_p2[0:0] === 1'b1) ? r_1_fu_304_p2 : ap_phi_mux_r_i2_phi_fu_168_p4);

assign tmp_i_fu_256_p1 = tmp_9_i_fu_250_p2;

assign tmp_i_mid2_fu_238_p3 = {{tmp_fu_234_p1}, {3'd0}};

assign tmp_i_mid2_v_v_fu_226_p3 = ((exitcond_i_fu_212_p2[0:0] === 1'b1) ? r_fu_206_p2 : ap_phi_mux_r_i_phi_fu_135_p4);

assign tmp_s_fu_267_p3 = {{tmp_i_mid2_v_v_reg_405}, {3'd0}};

endmodule //dct
